image: maven:latest

stages:
    - preparation
    - build
    - test
    - deploy


determine version:
  stage: preparation
  image: gittools/gitversion
  script:
    - pwd
    - dotnet /app/GitVersion.dll /output json /showvariable FullSemVer > version.txt
    - cat version.txt
  artifacts:
    paths:
      - version.txt
    expire_in: 1 hr

build1:
    stage: build
    script:
        - mvn compile
        
test1:
    stage: test
    script:
        - mvn test
        - cat target/site/jacoco/index.html
    artifacts:
        paths:
            - target/site/jacoco/

pages:
    stage: deploy
    dependencies:
        - test1
    script:
        - mv target/site/jacoco/ public/
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master

docker:
    stage: deploy
    image: docker:latest
    dependencies:
    script:
        - echo $dockerww | docker login -u demdiran --password-stdin
        - docker image build -t fifteen:1.1 .
        - docker image tag fifteen:1.1 demdiran/fifteen:1.1
        - docker image push demdiran/fifteen:1.1
    only:
        - master