image: maven:latest

stages:
    - build
    - test
    - deploy

build1:
    stage: build
    script:
        - mvn compile
        
test1:
    stage: test
    script:
        - mvn test
    artifacts:
        paths:
            - target/site/jacoco/index.html

pages:
    stage: deploy
    dependencies:
        - test1
    script:
        - mv target/site/jacoco/ public/
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master