

stages:
    - build
    - test
    - deploy

build1:
    stage: build
    image: maven:latest
    script:
        - mvn compile
        
test1:
    stage: test
    image: maven:latest
    script:
        - mvn test
        - cat target/site/jacoco/index.html
        - mvn pl.project13.maven:git-commit-id-plugin:revision
    artifacts:
        paths:
            - target/site/jacoco/
            - target/git.properties
        expire_in: 10 minutes

pages:
    stage: deploy
    image: maven:latest
    dependencies:
        - test1
    script:
        - mv target/site/jacoco/ public/
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master

docker:
    stage: deploy
    image: maven:latest
    dependencies:
    script:
        #- echo $dockerww | docker login -u demdiran --password-stdin
        - mvn deploy
        #- docker-compose up
        #- mvn deploy
        #- docker image push demdiran/fifteen:1.1
    artifacts:
        paths:
            - /
        expire_in: 10 min
    only:
        - master