stages:
    - build
    - test
    - deploy

build1:
    stage: build
    image: maven:latest
    script:
        - mvn compile
        
test1:
    stage: test
    image: maven:latest
    script:
        - mvn test
        - cat target/site/jacoco/index.html
    artifacts:
        paths:
            - target/site/jacoco/
        expire_in: 10 minutes
        
docker_login:
    stage: test
    image: docker:latest
    dependencies:
    script:
        - echo $dockerww | docker login -u demdiran --password_stdin

pages:
    stage: deploy
    image: maven:latest
    dependencies:
        - test1
    script:
        - mv target/site/jacoco/ public/
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master



docker_push:
    stage: deploy
    image: maven:latest
    dependencies:
        - docker_login
    script:
        - mvn deploy
    only:
        - master