image: maven:latest

stages:
    - build
    - test
    - deploy

build1:
    stage: build
    script:
        - mvn compile
        
test1:
    stage: test
    script:
        - mvn test
    artifacts:
        paths:
            - target/site/jacoco/

pages:
    stage: deploy
    dependencies:
        - test1
    script:
        - mv target/site/jacoco/ public/
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master

docker:
    stage: deploy
    image: docker:latest
    dependencies:
    script:
        - docker login -u demdiran --password-stdin $dockerww
        - docker image build -t fifteen:1.1 .
        - docker image tag fifteen:1.1 demdiran/fifteen:1.1
        - docker image push demdiran/fifteen:1.1
    only:
        - master