image: maven:latest

stages:
    - build
    - test
    - deploy

build1:
    stage: build
    script:
        - mvn compile
        
test1:
    stage: test
    script:
        - mvn test
        - cat target/site/jacoco/index.html
        - mvn pl.project13.maven:git-commit-id-plugin:revision
    artifacts:
        paths:
            - target/site/jacoco/
            - target/git.properties
        expire_in: 10 minutes

pages:
    stage: deploy
    dependencies:
        - test1
    script:
        - mv target/site/jacoco/ public/
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master

docker:
    stage: deploy
    dependencies:
        - test1
    image: docker:latest
    dependencies:
    script:
        - file="./target/git.properties"
        - head -n -1 $file > temp.properties ; mv temp.properties $file
        - if [ -f "$file" ]
        - then
        -   echo "$file found."
        -   echo "User Id       = " ${git.commit.id.abbrev}
        - else
        -   echo "$file not found."
        - fi
        - echo $dockerww | docker login -u demdiran --password-stdin
        - docker image build -t fifteen:1.1 .
        - docker image tag fifteen:1.1 demdiran/fifteen:1.1
        - docker image push demdiran/fifteen:1.1
    only:
        - master